version: '2'

networks:
  users_actions_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.100.1.0/24
          ip_range: 172.100.1.0/24
          gateway: 172.100.1.254

volumes:
  pgdata:
    driver: local

  redisdata:
    driver: local

services:
  django:
    restart: always
    build: ./myproject_site
    expose:
      - "8000"
    env_file:
      - common.env
    links:
      - postgres:postgres
      - redis:redis
# Start Development
    environment:
      - DEBUG=true
    volumes:
      - ./myproject_site:/srv/myproject_site
      - /usr/src/app/static
# End Development
    command: /usr/local/bin/uwsgi  --http :8000 --wsgi-file ./myproject_site/wsgi.py
    networks:
      users_actions_net:
        ipv4_address: 172.100.1.2
        aliases:
          - django

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "18080:80"
    volumes:
      - /www/static
    volumes_from:
      - django
    links:
      - django:django
    networks:
      users_actions_net:
        ipv4_address: 172.100.1.1
        aliases:
          - nginx

  postgres:
    restart: always
    build: ./postgis/
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      users_actions_net:
        ipv4_address: 172.100.1.3
        aliases:
          - postgres

  redis:
    restart: always
    image: redis:latest
    ports:
      - "16379:6379"
    volumes:
      - redisdata:/data
    networks:
      users_actions_net:
        ipv4_address: 172.100.1.4
        aliases:
          - redis
